// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(NormasDb))]
    [Migration("20251004215232_CreacionBaseDeDatos")]
    partial class CreacionBaseDeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // Definimos las entidades sin datos hardcodeados
            modelBuilder.Entity("Backend.Models.Actividad", b =>
            {
                b.Property<int>("IdActividad")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id_Actividad");
                b.HasKey("IdActividad");
                b.ToTable("Actividad");
            });

            modelBuilder.Entity("Backend.Models.Auditoria", b =>
            {
                b.Property<int>("IdAuditoria")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id_Auditoria");
                b.HasKey("IdAuditoria");
                b.ToTable("auditoria");
            });

            modelBuilder.Entity("Backend.Models.Dominio", b =>
            {
                b.Property<int>("IdDominio")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id_Dominio");
                b.HasKey("IdDominio");
                b.ToTable("Dominio");
            });

            modelBuilder.Entity("Backend.Models.Proceso", b =>
            {
                b.Property<int>("IdProceso")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id_Proceso");
                b.HasKey("IdProceso");
                b.ToTable("Proceso");
            });

            modelBuilder.Entity("Backend.Models.Subdominio", b =>
            {
                b.Property<int>("IdSubdominio")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id_Subdominio");
                b.HasKey("IdSubdominio");
                b.ToTable("Subdominio");
            });

            modelBuilder.Entity("backend.Models.Usuario.Rol", b =>
            {
                b.Property<int>("IdRol")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("idRol");
                b.HasKey("IdRol");
                b.ToTable("rol");
            });

            modelBuilder.Entity("backend.Models.Usuario.Usuario", b =>
            {
                b.Property<int>("Id_Usuario")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                b.HasKey("Id_Usuario");
                b.ToTable("usuarios");
                // SIN DATOS HARDCODEADOS - los datos vienen de los archivos SQL
            });
#pragma warning restore 612, 618
        }
    }
}
