// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(NormasDb))]
    [Migration("20251017062324_AgregarDebeRestablecerContrasena")]
    partial class AgregarDebeRestablecerContrasena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Actividad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("Documentos")
                        .HasColumnType("longtext")
                        .HasColumnName("Documentos");

                    b.Property<string>("EstadoImplementacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("EstadoImplementacion");

                    b.Property<DateTime?>("FechaCompromiso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCompromiso");

                    b.Property<DateTime?>("FechaControl")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaControl");

                    b.Property<int>("FuncionariosResponsablesId")
                        .HasColumnType("int")
                        .HasColumnName("FuncionariosResponsablesId");

                    b.Property<string>("Implementable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Sí")
                        .HasColumnName("Implementable");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PorcentajeAvance");

                    b.Property<int>("SubdominioId")
                        .HasColumnType("int")
                        .HasColumnName("SubdominioId");

                    b.HasKey("IdActividad");

                    b.HasIndex("FuncionariosResponsablesId");

                    b.HasIndex("SubdominioId");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("Backend.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Auditoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("longtext")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("longtext")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion_ip");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_evento");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Modulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modulo");

                    b.Property<string>("Navegador")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("navegador");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("FechaEvento");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Modulo");

                    b.HasIndex("TipoEvento");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Dominio", b =>
                {
                    b.Property<int>("IdDominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Dominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDominio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdDominio");

                    b.ToTable("Dominio");
                });

            modelBuilder.Entity("Backend.Models.Proceso", b =>
                {
                    b.Property<int>("IdProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Proceso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProceso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Codigo");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPorId");

                    b.Property<int>("DominioId")
                        .HasColumnType("int")
                        .HasColumnName("DominioId");

                    b.Property<string>("EstadoImplementacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Sí")
                        .HasColumnName("EstadoImplementacion");

                    b.Property<DateTime?>("FechaConclusionImplementacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaConclusionImplementacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("MarcoNormativo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MarcoNormativo");

                    b.Property<int>("ModificadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPorId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PorcentajeAvance");

                    b.Property<int>("PrioridadImplementacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("PrioridadImplementacion");

                    b.HasKey("IdProceso");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("DominioId");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Proceso");
                });

            modelBuilder.Entity("Backend.Models.Subdominio", b =>
                {
                    b.Property<int>("IdSubdominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Subdominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSubdominio"));

                    b.Property<string>("IndicadoresAsociados")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("indicadoresAsociados");

                    b.Property<string>("PracticasGobierno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PracticasGobierno");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcesoId");

                    b.HasKey("IdSubdominio");

                    b.HasIndex("ProcesoId");

                    b.ToTable("Subdominio");
                });

            modelBuilder.Entity("backend.Models.Usuario.RecuperacionContrasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecuperacionesContrasena");
                });

            modelBuilder.Entity("backend.Models.Usuario.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idRol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("backend.Models.Usuario.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("DebeRestablecerContrasena")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("fechaBloqueado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("intentosLoginFallidos")
                        .HasColumnType("int");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("departamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("fechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("fechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("correo_electronico")
                        .IsUnique();

                    b.HasIndex("idRol");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            DebeRestablecerContrasena = false,
                            intentosLoginFallidos = 0,
                            cedula = "admin",
                            contrasena = "admin123",
                            correo_electronico = "admin@micitt.go.cr",
                            departamento = "TI",
                            estado = true,
                            fechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            fechaUltimaModificacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            idRol = 1,
                            nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("Backend.Models.Actividad", b =>
                {
                    b.HasOne("backend.Models.Usuario.Usuario", "FuncionariosResponsables")
                        .WithMany()
                        .HasForeignKey("FuncionariosResponsablesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subdominio", "Subdominio")
                        .WithMany("Actividades")
                        .HasForeignKey("SubdominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuncionariosResponsables");

                    b.Navigation("Subdominio");
                });

            modelBuilder.Entity("Backend.Models.Auditoria", b =>
                {
                    b.HasOne("backend.Models.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Proceso", b =>
                {
                    b.HasOne("backend.Models.Usuario.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Dominio", "Dominio")
                        .WithMany("Procesos")
                        .HasForeignKey("DominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Dominio");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("Backend.Models.Subdominio", b =>
                {
                    b.HasOne("Backend.Models.Proceso", "Proceso")
                        .WithMany("Subdominios")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("backend.Models.Usuario.RecuperacionContrasena", b =>
                {
                    b.HasOne("backend.Models.Usuario.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Usuario.Usuario", b =>
                {
                    b.HasOne("backend.Models.Usuario.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Backend.Models.Dominio", b =>
                {
                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("Backend.Models.Proceso", b =>
                {
                    b.Navigation("Subdominios");
                });

            modelBuilder.Entity("Backend.Models.Subdominio", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("backend.Models.Usuario.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
