// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(NormasDb))]
    [Migration("20260225000000_AddRolDocumentoEnActividad")]
    partial class AddRolDocumentoEnActividad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Actividad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("Documentos")
                        .HasColumnType("longtext")
                        .HasColumnName("Documentos");

                    b.Property<string>("EstadoImplementacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("EstadoImplementacion");

                    b.Property<DateTime?>("FechaCompromiso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCompromiso");

                    b.Property<DateTime?>("FechaControl")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaControl");

                    b.Property<int>("FuncionariosResponsablesId")
                        .HasColumnType("int")
                        .HasColumnName("FuncionariosResponsablesId");

                    b.Property<string>("Implementable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Sí")
                        .HasColumnName("Implementable");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PorcentajeAvance");

                    b.Property<int>("SubdominioId")
                        .HasColumnType("int")
                        .HasColumnName("SubdominioId");

                    b.HasKey("IdActividad");

                    b.HasIndex("FuncionariosResponsablesId");

                    b.HasIndex("SubdominioId");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("backend.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Auditoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("longtext")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("longtext")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion_ip");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_evento");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Modulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modulo");

                    b.Property<string>("Navegador")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("navegador");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("FechaEvento");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Modulo");

                    b.HasIndex("TipoEvento");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("backend.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Documento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int")
                        .HasColumnName("ActividadId");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Confidencialidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Interna")
                        .HasColumnName("Confidencialidad");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPorId");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<int?>("EliminadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("EliminadoPorId");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaAlerta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaAlerta");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaModificacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPorId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RolEnActividad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Anexo")
                        .HasColumnName("RolEnActividad");

                    b.Property<DateTime>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RowVersion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("RowVersion"));

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TipoDocumento");

                    b.Property<int?>("VersionActualId")
                        .HasColumnType("int")
                        .HasColumnName("VersionActualId");

                    b.HasKey("IdDocumento");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("EliminadoPorId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IDX_Estado");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("IDX_FechaVencimiento");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("VersionActualId");

                    b.HasIndex("ActividadId", "Estado", "Eliminado")
                        .HasDatabaseName("IDX_Documentos_Actividad_Estado");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("backend.Models.Dominio", b =>
                {
                    b.Property<int>("IdDominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Dominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDominio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdDominio");

                    b.ToTable("Dominio");
                });

            modelBuilder.Entity("backend.Models.MetadatoDocumento", b =>
                {
                    b.Property<int>("IdMetadatoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_MetadatoDocumento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMetadatoDocumento"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Clave");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPorId");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentoId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext")
                        .HasColumnName("Valor");

                    b.HasKey("IdMetadatoDocumento");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("DocumentoId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("UQ_Documento_Clave");

                    b.ToTable("metadatos_documento");
                });

            modelBuilder.Entity("backend.Models.Proceso", b =>
                {
                    b.Property<int>("IdProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Proceso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProceso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Codigo");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPorId");

                    b.Property<int>("DominioId")
                        .HasColumnType("int")
                        .HasColumnName("DominioId");

                    b.Property<string>("EstadoImplementacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Sí")
                        .HasColumnName("EstadoImplementacion");

                    b.Property<DateTime?>("FechaConclusionImplementacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaConclusionImplementacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("MarcoNormativo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MarcoNormativo");

                    b.Property<int>("ModificadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPorId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PorcentajeAvance");

                    b.Property<int>("PrioridadImplementacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("PrioridadImplementacion");

                    b.HasKey("IdProceso");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("DominioId");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Proceso");
                });

            modelBuilder.Entity("backend.Models.RelacionDocumento", b =>
                {
                    b.Property<int>("IdRelacionDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_RelacionDocumento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRelacionDocumento"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPorId");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("DocumentoDestinoId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentoDestinoId");

                    b.Property<int>("DocumentoOrigenId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentoOrigenId");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("Orden");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TipoRelacion");

                    b.HasKey("IdRelacionDocumento");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("DocumentoDestinoId");

                    b.HasIndex("DocumentoOrigenId", "DocumentoDestinoId", "TipoRelacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Relacion");

                    b.ToTable("relaciones_documento");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idRol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("backend.Models.Subdominio", b =>
                {
                    b.Property<int>("IdSubdominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Subdominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSubdominio"));

                    b.Property<string>("IndicadoresAsociados")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("indicadoresAsociados");

                    b.Property<string>("PracticasGobierno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PracticasGobierno");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int")
                        .HasColumnName("ProcesoId");

                    b.HasKey("IdSubdominio");

                    b.HasIndex("ProcesoId");

                    b.ToTable("Subdominio");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("DebeRestablecerContrasena")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("departamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("fechaBloqueado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("fechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("intentosLoginFallidos")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("ultimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("correo_electronico")
                        .IsUnique();

                    b.HasIndex("idRol");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("backend.Models.UsuarioContrasena.RecuperacionContrasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecuperacionesContrasena");
                });

            modelBuilder.Entity("backend.Models.VersionDocumento", b =>
                {
                    b.Property<int>("IdVersionDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_VersionDocumento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVersionDocumento"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("ChecksumSHA256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ChecksumSHA256");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext")
                        .HasColumnName("Comentario");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentoId");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaSubida")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MimeType");

                    b.Property<string>("NombreArchivoOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NombreArchivoOriginal");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int")
                        .HasColumnName("NumeroVersion");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("RutaArchivo");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int")
                        .HasColumnName("SubidoPorId");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("TamanoBytes");

                    b.Property<string>("TipoAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TipoAlmacenamiento");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("URL");

                    b.Property<string>("VersionTexto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("VersionTexto");

                    b.HasKey("IdVersionDocumento");

                    b.HasIndex("ChecksumSHA256")
                        .HasDatabaseName("IDX_ChecksumSHA256");

                    b.HasIndex("SubidoPorId");

                    b.HasIndex("DocumentoId", "NumeroVersion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Documento_NumeroVersion");

                    b.ToTable("versiones_documento");
                });

            modelBuilder.Entity("backend.Models.Actividad", b =>
                {
                    b.HasOne("backend.Models.Usuario", "FuncionariosResponsables")
                        .WithMany()
                        .HasForeignKey("FuncionariosResponsablesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Subdominio", "Subdominio")
                        .WithMany("Actividades")
                        .HasForeignKey("SubdominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuncionariosResponsables");

                    b.Navigation("Subdominio");
                });

            modelBuilder.Entity("backend.Models.Auditoria", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Documento", b =>
                {
                    b.HasOne("backend.Models.Actividad", "Actividad")
                        .WithMany("DocumentosVinculados")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "EliminadoPor")
                        .WithMany()
                        .HasForeignKey("EliminadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.VersionDocumento", "VersionActual")
                        .WithMany()
                        .HasForeignKey("VersionActualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actividad");

                    b.Navigation("CreadoPor");

                    b.Navigation("EliminadoPor");

                    b.Navigation("ModificadoPor");

                    b.Navigation("VersionActual");
                });

            modelBuilder.Entity("backend.Models.MetadatoDocumento", b =>
                {
                    b.HasOne("backend.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Documento", "Documento")
                        .WithMany("Metadatos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("backend.Models.Proceso", b =>
                {
                    b.HasOne("backend.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Dominio", "Dominio")
                        .WithMany("Procesos")
                        .HasForeignKey("DominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Dominio");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("backend.Models.RelacionDocumento", b =>
                {
                    b.HasOne("backend.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Documento", "DocumentoDestino")
                        .WithMany("RelacionesComoDestino")
                        .HasForeignKey("DocumentoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Documento", "DocumentoOrigen")
                        .WithMany("RelacionesComoOrigen")
                        .HasForeignKey("DocumentoOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("DocumentoDestino");

                    b.Navigation("DocumentoOrigen");
                });

            modelBuilder.Entity("backend.Models.Subdominio", b =>
                {
                    b.HasOne("backend.Models.Proceso", "Proceso")
                        .WithMany("Subdominios")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.HasOne("backend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("backend.Models.UsuarioContrasena.RecuperacionContrasena", b =>
                {
                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.VersionDocumento", b =>
                {
                    b.HasOne("backend.Models.Documento", "Documento")
                        .WithMany("Versiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("backend.Models.Actividad", b =>
                {
                    b.Navigation("DocumentosVinculados");
                });

            modelBuilder.Entity("backend.Models.Documento", b =>
                {
                    b.Navigation("Metadatos");

                    b.Navigation("RelacionesComoDestino");

                    b.Navigation("RelacionesComoOrigen");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("backend.Models.Dominio", b =>
                {
                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("backend.Models.Proceso", b =>
                {
                    b.Navigation("Subdominios");
                });

            modelBuilder.Entity("backend.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.Models.Subdominio", b =>
                {
                    b.Navigation("Actividades");
                });
#pragma warning restore 612, 618
        }
    }
}
